booksite/urls.py
# Copyright 2017 Mirko Lelansky <mlelansky@mail.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""booksite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bookstore/', include("bookstore.urls")),
    url(r'^$', RedirectView.as_view(url='/bookstore/', permanent=True))
]

bookstore/urls.py
# Copyright 2017 Mirko Lelansky <mlelansky@mail.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from . import views

app_name = 'bookstore'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^ratings/$', cache_page(60 * 15)(views.RatingsListView.as_view()), name="ratings"),
    url(r'^rating/$', views.RatingFormView.as_view(), name="rating")
]

bookstore/models.py
# Copyright 2017 Mirko Lelansky <mlelansky@mail.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.db import models

class Author(models.Model):
    """
    This class represents the author of a book.
    """
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    def __str__(self):
        return self.firstname + " " + self.lastname

    class Meta:
        ordering = ['lastname', 'firstname']

class Book(models.Model):
    """
    This class represents the books.
    """
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    isbn = models.CharField("ISBN", max_length=13, unique=True)
    summary = models.TextField(max_length=1000, null=True, blank=True)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Rating(models.Model):
    """
    This class represents the rating of a book.
    """
    book = models.ForeignKey("Book", on_delete=models.CASCADE)
    stars = models.PositiveSmallIntegerField(choices=((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)), default=0)

bookstore/views.py
# Copyright 2017 Mirko Lelansky <mlelansky@mail.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import Author, Book, Rating

def index(request):
    """
    This is the base index page.
    """
    authors_count = Author.objects.count()
    books_count = Book.objects.count()

    return render(request, "bookstore/index.html", context={
        "authors_count": authors_count,
        "books_count": books_count
    })

class RatingsListView(ListView):
    """
    This class represents the current top ratings.
    """
    template_name = "bookstore/ratings.html"

    def get_queryset(self):
        """
        This method returns the current ten top ratings.
        """
        ratings = Rating.objects.filter(stars__gte=1).annotate(scount=Count('stars'))
        ratings_converted = self._convert_ratings(ratings)
        result = [(key, self._calculate_star(value["values"], value["weights"])) for key, value in ratings_converted.items()]
        result.sort(key=lambda x: x[1])
        return result[:10]

    def _convert_ratings(self, ratings):
        """
        """
        result = {}
        for rating in ratings:
            title = rating.book.title
            value = rating.scount
            weight = rating.stars

            if title not in result:
                result[title] = {}
            if "values" not in result[title]:
                result[title]["values"] = []
            if "weights" not in result[title]:
                result[title]["weights"] = []

            result[title]["values"].append(value)
            result[title]["weights"].append(weight)
        return result

    def _calculate_star(self, values, weights):
        s = sum(values)
        sw = sum([values[i] * weights[i] for i in range(len(values))])
        return round(sw/s, 2)

class RatingFormView(CreateView):
    """
    This class represents the rating of a book.
    """
    fields = ["book", "stars"]
    model = Rating
    success_url = reverse_lazy("bookstore:ratings")

bookstore/templates/base_generic.html
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta charset="utf-8">
        {% block meta %}{% endblock %}
        <title>
            {% block title %}Bookstore Application{% endblock %}
        </title>
        {% block links %}{% endblock %}
    </head>
    <body>
        <header id="header">
            {% block header %}
                <h1>Bookstore Application</h1>
            {% endblock %}
            {% block navigation %}
                <nav>
                    <ul>
                        <li><a href="{% url 'bookstore:index' %}">Home</a></li>
                        <li><a href="{% url 'bookstore:ratings' %}">Ratings</a></li>
                        <li><a href="{% url 'bookstore:rating' %}">Rate</a></li>
                    </ul>
                </nav>
            {% endblock %}
        </header>
        <section id="content">
            {% block content %}{% endblock %}
        </section>
        <aside id="pagination">
            {% block pagination %}
                {% if is_paginated %}
                    <nav>
                        <ul>
                            {% if page_obj.has_previous %}
                                <li><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a></li>
                            {% endif %}
                                <li><span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>
                            {% if page_obj.has_next %}
                                <li><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            {% endblock %}
        </aside>
        <footer id="footer">
            {% block footer %}{% endblock %}
        </footer>
    </body>
</html>

bookstore/templates/bookstore/index.html
{% extends "base_generic.html" %}

{% block content %}

<p>The shop has the following records.</p>

<ul>
    <li><strong>Authors: </strong>{{ authors_count }}</li>
    <li><strong>Books: </strong>{{ books_count }}</li>
</ul>

{% endblock %}

bookstore/templates/bookstore/rating_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

bookstore/templates/bookstore/ratings.html
{% extends "base_generic.html" %}

{% block content %}
    {% if object_list %}
        <table>
            <thead>
                <tr>
                    <th>Book Title</th>
                    <th>Stars</th>
                </tr>
            </thead>
            <tfoot>
            </tfoot>
            <tbody>
                {% for rating in object_list %}
                    <tr>
                        <td>
                            {{ rating.0 }}
                        </td>
                        <td>
                            {{ rating.1 }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no rating.</p>
    {% endif %}

{% endblock %}